"""Changed the model structure

Revision ID: ab9bbdb3cc00
Revises: 46f778815db7
Create Date: 2018-02-15 12:35:28.855143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9bbdb3cc00'
down_revision = '46f778815db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
